Feat: Manual Destroy Step

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -172,6 +172,64 @@ jobs:
             docker compose --env-file .env.${IMAGE_TAG} -f docker-compose.yaml up -d
           EOF
 
+
+      - name: Terraform Destroy (Manual Only)
+
+        on:
+          workflow_dispatch:
+            inputs:
+              environment:
+                description: "Environment to destroy (dev / uat / prod)"
+                required: true
+              confirm:
+                description: "Type DESTROY to confirm"
+                required: true
+
+  destroy:
+    runs-on: ubuntu-latest
+
+    steps:
+
+      - name: Terraform Destroy (Manual Only)
+
+        on:
+          workflow_dispatch:
+            inputs:
+              environment:
+                description: "Environment to destroy (dev / uat / prod)"
+                required: true
+              confirm:
+                description: "Type DESTROY to confirm"
+                required: true
+
+
+      - name: Safety check
+        run: |
+          if [ "${{ inputs.confirm }}" != "DESTROY" ]; then
+            echo "❌ Confirmation failed. Type DESTROY exactly."
+            exit 1
+          fi
+
+      - uses: actions/checkout@v4
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_wrapper: false
+
+      - name: Terraform destroy (manual approval)
+        working-directory: terraform
+        run: |
+          terraform init -backend-config="key=env/${{ inputs.environment }}/terraform.tfstate"
+          terraform destroy -var="environment=${{ inputs.environment }}"
+
       # - name: Verify Deployment#1 - Backend
       #   run: |
       #     sleep 15
